export const locationsArray = [
    {
      name: 'АО «ТД «БЕЛАЗ»',
      country: 'Российская Федерация',
      address: 'г. Москва',
      status: 1,
      coordinates: [55.538427, 37.507187]
    },
    {
      name: 'ООО «Торговый Дом БМЗ»',
      country: 'Российская Федерация',
      address: 'г. Москва',
      status: 1,
      coordinates: [55.793227, 37.559883]
    },
    {
      name: 'ООО «Торговый дом ИНТЕГРАЛ»',
      country: 'Российская Федерация',
      address: 'г. Москва',
      status: 1,
      coordinates: [55.800220, 37.538790]
    },
    {
      name: 'ООО "Торговый дом "Электромодуль"',
      country: 'Российская Федерация',
      address: 'г. Москва',
      status: 1,
      coordinates: [55.754081, 37.736240]
    },
    {
      name: 'ООО ПО «МЛМ Воздухотехника» (совместное предприятие)',
      country: 'Российская Федерация',
      address: 'г. Москва',
      status: 2,
      coordinates: [55.680372, 37.427210]
    },
    {
      name: 'АО "Горизонт-РУС"',
      country: 'Российская Федерация',
      address: 'г. Москва',
      status: 1,
      coordinates: [55.905396, 37.384819]
    },
    {
      name: 'ООО «МАЗ-РУС»',
      country: 'Российская Федерация',
      address: 'Московская обл., Красногорский р-н, п.о. Путилково',
      status: 1,
      coordinates: [55.867430, 37.395491]
    },
    {
      name: 'ООО "ПО НЛМ" (совместное предприятие)',
      country: 'Российская Федерация',
      address: 'Московская обл., г. Электросталь',
      status: 2,
      coordinates: [55.786121, 38.451074]
    },
    {
      name: 'ООО «Торговый дом МТЗ»',
      country: 'Российская Федерация',
      address: 'Московская обл., д. Долматово',
      status: 1,
      coordinates: [55.334388, 37.724310]
    },
    {
      name: 'ООО «Торговый дом «Минский моторный завод»',
      country: 'Российская Федерация',
      address: 'Московская обл., г. Ногинск',
      status: 1,
      coordinates: [55.874117, 38.451434]
    },
    {
      name: 'ООО «Торговый дом «БАТЭ»',
      country: 'Российская Федерация',
      address: 'Московская обл., г. Красногорск',
      status: 1,
      coordinates: [55.833405, 37.291735]
    },
    {
      name: 'ООО «Торговый дом «БКМ»',
      country: 'Российская Федерация',
      address: 'Московская область, Одинцовский район, г. Одинцово',
      status: 1,
      coordinates: [55.664136, 37.293936]
    },
    {
      name: 'ООО «ЦТП «КМА-БЕЛАЗ»',
      country: 'Российская Федерация',
      address: 'г. Губкин',
      status: 6,
      coordinates: [51.277520, 37.564841]
    },
    {
      name: 'АО «Брянсксельмаш»',
      country: 'Российская Федерация',
      address: 'г. Брянск',
      status: 2,
      coordinates: [53.211778, 34.435740]
    },
    {
      name: 'ООО «Амкодор-Брянск»',
      country: 'Российская Федерация',
      address: 'г. Брянск',
      status: 2,
      coordinates: [53.250518, 34.459428]
    },
    {
      name: 'ООО «Ветразь-Восток»',
      country: 'Российская Федерация',
      address: 'г. Рудня',
      status: 1,
      coordinates: [54.956492, 31.052828]
    },
    {
      name: 'ООО «Торговый Дом БМЗ»',
      country: 'Российская Федерация',
      address: 'г. Санкт-Петербург',
      status: 1,
      coordinates: [59.878432, 30.258340]
    },
    {
      name: 'ООО «МВитязь»',
      country: 'Российская Федерация',
      address: 'г. Санкт-Петербург',  
      status: 1,
      coordinates: [59.942173, 30.381256]
    },
    {
      name: 'ООО «С- Витязь»',
      country: 'Российская Федерация',
      address: 'г. Санкт-Петербург',
      status: 1,
      coordinates: [59.842033, 30.131237 ],
    },
    {
      name: 'СП АО "Интеграл СПб"',
      country: 'Российская Федерация',
      address: 'г. Санкт-Петербург',
      status: 1,
      coordinates: [ 59.955390, 30.468806 ],
    },
    {
      name: 'ООО "МЛМ Невский лифт" (совместное предприятие)',
      country: 'Российская Федерация',
      address: 'г. Санкт-Петербург',
      status: 2,
      coordinates: [ 60.000020, 30.256301 ],
    },
    {
      name: 'ООО "СП ЛадогаМАЗсервис»',
      country: 'Российская Федерация',
      address: 'г. Всеволожск',
      status: 1,
      coordinates: [ 60.001343, 30.773829],
    },
    {
      name: 'ООО «Торговый дом МТЗ-Северо-Запад»',
      country: 'Российская Федерация',
      address: 'п. Тоншалово',
      status: 1,
      coordinates: [ 59.187545, 37.934741],
    },
    {
      name: 'Мультибрендовый торгово-сервисный центр "МАЗ-БЕЛАРУСЬ"',
      country: 'Российская Федерация',
      address: 'г. Санкт-Петербург',
      status: '4a',
      coordinates: [ 59.9343,  30.3351 ],
    },
    {
      name: 'ООО "Могилев Кубань Лифт"',
      country: 'Российская Федерация',
      address: 'г. Краснодар',
      status: '5',
      coordinates: [ 44.992734, 39.065854 ],
    },
    {
      name: 'ООО «Минский трансформатор»',
      country: 'Российская Федерация',
      address: 'г. Ростов-на-Дону',
      status: 1,
      coordinates: [ 47.238728, 39.687731 ],
    },
    {
      name: 'Мультибрендовый торгово-сервисный центр "BELARUS"',
      country: 'Российская Федерация',
      address: 'г. Краснодар',
      status: '4a',
      coordinates: [ 45.008827, 39.127676 ],
    },
    {
      name: 'ООО «Торговый дом МТЗ – Ставрополь»',
      country: 'Российская Федерация',
      address: 'г. Ставрополь',
      status: 1,
      coordinates: [ 45.033069,  41.955411 ],
    },
    {
      name: 'ООО "Региональный центр МАЗ-ЮГ"',
      country: 'Российская Федерация',
      address: 'г. Ростов-на-Дону',
      status: '4c',
      coordinates: [ 47.2357,  39.7015 ],
    },
    {
      name: 'ООО СП «Нижэкотранс»',
      country: 'Российская Федерация',
      address: 'г. Ворсма',
      status: 1,
      coordinates: [ 55.988610,  43.274677 ],
    },
    {
      name: 'ООО «ТПК МТЗ-Татарстан»',
      country: 'Российская Федерация',
      address: 'г. Елабуга',
      status: '4b',
      coordinates: [ 55.840472,  52.068663 ],
    },
    {
      name: 'ООО "ТД "Белкард"',
      country: 'Российская Федерация',
      address: 'г. Казань',
      status: 5,
      coordinates: [ 55.827803,  49.063232 ],
    },
    {
      name: 'ООО "БКМ СИБИРЬ"',
      country: 'Российская Федерация',
      address: 'г. Новосибирск',
      status: 1,
      coordinates: [ 54.950149,  82.901071 ],
    },
    {
      name: 'ООО ТД "Гомсельмаш-Сибирь"',
      country: 'Российская Федерация',
      address: 'п. Элитный',
      status: 1,
      coordinates: [ 54.918022,  82.959210 ],
    },
    {
      name: 'ООО «Торговый дом МТЗ – Сибирь»',
      country: 'Российская Федерация',
      address: 'п. Элитный',
      status: '4b',
      coordinates: [ 54.918022,  82.959210 ],
    },
    {
      name: 'СООО «Омсклидагромаш»',
      country: 'Российская Федерация',
      address: 'г. Омск',
      status: 6,
      coordinates: [ 54.929503,  73.289924 ],
    },
    {
      name: 'ООО «МЛМ-Усолье»',
      country: 'Российская Федерация',
      address: 'г. Усолье-Сибирское',
      status: 6,
      coordinates: [ 52.753427,  103.633721 ],
    },
    {
      name: 'ООО "Б-24"',
      country: 'Российская Федерация',
      address: 'пгт. Грамотеено',
      status: '4c',
      coordinates: [ 54.488970,  86.377812 ],
    },
    {
      name: 'ООО "Белорусские тракторы"',
      country: 'Российская Федерация',
      address: 'г. Владивосток',
      status: '4c',
      coordinates: [ 43.115542,  131.885494 ]
    },
    {
      name: 'СП ЧАО «АТЛАНТ-Украина»',
      country: 'Украина',
      address: 'г. Киев',
      status: 6,
      coordinates: [ 50.492814,  30.599430 ],
    },
    {
      name: 'ООО Торговый дом «Витязь»',
      country: 'Украина',
      address: 'г. Киев',
      status: 6,
      coordinates: [ 50.460024,  30.652988 ],
    },
    {
      name: 'ООО "ТД "Гомсельмаш-Украина"',
      country: 'Украина',
      address: 'г. Киев',
      status: 6,
      coordinates: [ 50.494235,  30.466102 ],
    },
    {
      name: 'ООО "УкрЛифтМаш"',
      country: 'Украина',
      address: 'г. Киев',
      status: 6,
      coordinates: [ 50.442393,  30.632533 ],
    },
    {
      name: 'ООО «АМКОДОР-УКРОСПЕЦМАШ»',
      country: 'Украина',
      address: 'г. Киев',
      status: 6,
      coordinates: [ 50.431860,  30.354936 ],
    },
    {
      name: 'ООО "ТД "МТЗ-Беларус-Украина"',
      country: 'Украина',
      address: 'с. Константиновка',
      status: 6,
      coordinates: [ 47.094789,  31.931317 ],
    },
    {
      name: 'ООО «Украгробелмаш»',
      country: 'Украина',
      address: 'г. Днепропетровск',
      status: 6,
      coordinates: [ 48.530271,  35.109512 ],
    },
    {
      name: 'ООО "Торговый дом МТЗ-Беларусь-Украина"',
      country: 'Украина',
      address: 'с. Константиновка',
      status: 6,
      coordinates: [ 47.094789,  31.931317 ],
    },
    {
      name: 'ООО "БКМ-Украина"',
      country: 'Украина',
      address: 'г. Луцк',
      status: 6,
      coordinates: [ 50.741684,  25.317741 ],
    },
    {
      name: 'ТОО «АСТАНАБЕЛАЗ СЕРВИС К»',
      country: 'Республика Казахстан',
      address: 'г. Караганда',
      status: 1,
      coordinates: [ 49.822495,  73.061177 ],
    },
    {
      name: 'ТОО «Казахстанский Белазавтосервис»',
      country: 'Республика Казахстан',
      address: 'г. Рудный-1',
      status: 6,
      coordinates: [ 52.964432,  63.133392 ],
    },
    {
      name: 'ТОО «Амкодор-Астана»',
      country: 'Республика Казахстан',
      address: 'г. Астана',
      status: 1,
      coordinates: [ 51.086732,  71.449195 ],
    },
    {
      name: 'ТОО «Торговый дом МАЗ-Казахстан»',
      country: 'Республика Казахстан',
      address: 'г. Астана',
      status: 1,
      coordinates: [ 51.183450,  71.420889 ],
    },
    {
      name: 'ТОО «Торговый Дом Белорусский Трактор»',
      country: 'Республика Казахстан',
      address: 'г. Астана',
      status: 1,
      coordinates: [ 51.208308,  71.500758 ],
    },
    {
      name: 'ТОО «КазАгроБел»',
      country: 'Республика Казахстан',
      address: 'г. Кокшетау',
      status: 6,
      coordinates: [ 53.285066,  69.386313 ],
    },
    {
      name: 'ООО «Торговый Дом МТЗ – Лидер»',
      country: 'Республика Молдова',
      address: 'г. Кишинев',
      status: 1,
      coordinates: [ 46.989701,  28.887196 ],
    },
    {
      name: 'ИП ООО «MAZ-TASHKENT»',
      country: 'Республика Узбекистан',
      address: 'г. Ташкент',
      status: 1,
      coordinates: [ 41.280515,  69.294882 ],
    },
    {
      name: 'ИП ООО «AMKODOR-TASHKENT»',
      country: 'Республика Узбекистан',
      address: 'г. Ташкент',
      status: 6,
      coordinates: [ 41.280515,  69.294882 ],
    },
    {
      name: 'СП ООО «AMKODOR-AGROTEXMASH»',
      country: 'Республика Узбекистан',
      address: 'г. Ташкент',
      status: 6,
      coordinates: [ 41.353476,  69.389178 ],
    },
    {
      name: 'ЗАО «Торговый дом БМЗ - Балтия»',
      country: 'Литовская Республика',
      address: 'г. Шяуляй',
      status: 6,
      coordinates: [ 55.913343,  23.322349 ],
    },
    {
      name: 'ООО «MAZ AUTO POLAND»',
      country: 'Республика Польша',
      address: 'г. Ламянки',
      status: 1,
      coordinates: [52.359865, 20.858980],
    },
    {
      name: 'Energis Sp. Z o.o.',
      country: 'Республика Польша',
      address: 'г. Варшава',
      status: 6,
      coordinates: [52.393643, 20.876227],
    },
    {
      name: 'ООО «МАЗ БАЛКАН»',
      country: 'Сербия',
      address: 'г. Крагуевац',
      status: 2,
      coordinates: [44.014745, 20.928797],
    },
    {
      name: 'BELARUS TRACTOR KFT ООО «Беларус Трактор»',
      country: 'Венгрия',
      address: 'г. Будапешт',
      status: 1,
      coordinates: [47.523123, 19.122662],
    },
    {
      name: 'BELIMPEX-Handel’s GmbH ООО "Белимпекс-Хандельс ГмбХ"',
      country: 'Германия',
      address: 'г. Лейпциг',
      status: 1,
      coordinates: [51.340484, 12.374643],
    },
    {
      name: 'MINSK TRACTOR PLANT LTD (АО «Минск Трактор Плант Лимитед»)',
      country: 'Ирландия',
      address: 'Дублин Роуд',
      status: 6,
      coordinates: [52.257373, -7.111549],
    },
    {
      name: 'BELARUS EQUIPMENT (IRELAND) Ltd (АО «БЕЛАРУС ЭКВИПМЕНТ (ИРЛАНДИЯ) ЛИМИТЕД»)',
      country: 'Ирландия',
      address: 'Дублин Роуд',
      status: 6,
      coordinates: [52.257847, -7.115664],
    },
    {
      name: 'Wave Industries Limited',
      country: 'Соединенное Королевство Великобритании',
      address: 'г. Ковентри, Ирлсдон, Соверейн Хаус, 12-14',
      status: 6,
      coordinates: [52.409369, -1.503591],
    },
    {
      name: 'BAT AGRO TRADE Eltd (ЕООО «Беларус Агро-трейд»)',
      country: 'Болгария',
      address: 'г. Плевен',
      status: 1,
      coordinates: [43.407974, 24.619579],
    },
    {
      name: 'АО "Белоруски лагери"',
      country: 'Болгария',
      address: 'г.София',
      status: 6,
      coordinates: [42.6932666, 23.3445452],
    },
  
    {
      name: 'BELARUS-AGROPANONKA DOO NOVI SAD (ООО «Беларус-Агропанонка»)',
      address: 'г. Нови Сад',
      status: 2,
      coordinates: [45.2646808, 19.8481989],
      country: 'Сербия',
    },
    {
      name: 'Belarus Tractor Slovakia SRO',
      address: 'Blatna na Ostrove',
      status: 6,
      coordinates: [47.9945202, 17.3946689],
      country: 'Словакия',
    },
    {
      name: 'BELARUS-AGRO-TRACTOR S.L. (ООО «Беларус-агро-трактор»)',
      address: 'г. Таранкон',
      status: 6,
      coordinates: [40.010173, -3.013902],
      country: 'Испания',
    },
    {
      name: 'СП ООО "Харбин Дон Цзин Гомель предприятие сельскохозяйственного машиностроения"',
      address: 'г. Харбин',
      status: 6,
      coordinates: [45.8407537, 126.6064951],
      country: 'Китайская Народная Республика',
    },
    {
      name: 'СП ООО "Чунцинское предприятие сельхозмашиностроения Цзуншень-Гомель"',
      address: 'г. Чунцин',
      status: 2,
      coordinates: [29.6262562, 106.6225712],
      country: 'Китайская Народная Республика',
    },
    {
      name: 'Harbin Dongjin Minsk Tractor Co., Ltd (СП ООО «Харбин Дон Цзин Минск Трактор»)',
      address: 'г. Харбин',
      status: 6,
      coordinates: [45.8407537, 126.6064951],
      country: 'Китайская Народная Республика',
    },
    {
      name: 'GOMSELMASH INDIA PRIVATE LIMITED',
      address: 'New Delhi',
      status: 6,
      coordinates: [28.5390873, 77.2818785],
      country: 'Индия',
    },
    {
      name: 'АО «МАЗ Азия»',
      address: 'Ta Thuong Hamlet',
      status: 2,
      coordinates: [20.9900427, 105.6857213],
      country: 'Социалистическая Республика Вьетнам',
    },
    {
      name: 'JSC «BELMACHINERY for International Trade»',
      address: 'Хургада',
      status: 6,
      coordinates: [27.234275, 33.834425],
      country: 'Египет',
    },
    {
      name: 'Филиал ОАО "Гомсельмаш" в Аргентине - Торговый дом "Полесье"',
      address: 'Ingeniero Huergo',
      status: 1,
      coordinates: [-39.080578, -66.803498],
      country: 'Аргентина',
    },
    {
      name: 'СП АО «MAZ VEN S.A.»',
      address: 'г. Каракас',
      status: 2,
      coordinates: [10.4891984, -66.8250368],
      country: 'Боливарианская Республика Венесуэла',
    },
    {
      name: 'VENEMINSK TRACTORES, C.A. (АО «ВЕНЕМИНСК ТРАКТОР»)',
      address: 'г. Каракас',
      status: 2,
      coordinates: [10.505982, -66.832258],
      country: 'Боливарианская Республика Венесуэла',
    },
    {
      name: 'BELARUS-MEKONG LLC. ЧООО «Беларус-Меконг»',
      address: 'Пномпень',
      status: 6,
      coordinates: [11.572714, 104.917190],
      country: 'Королевство Камбоджа',
    },
    


    {
      name: 'ОАО «МТЗ»',
      address: 'г. Москва',
      status: 1,
      coordinates: [55.758048, 37.637353],
      country: 'Российская Федерация',
    },
    {
      name: 'ОАО «МТЗ»',
      address: 'г. Ашхабад',
      status: 3,
      coordinates: [37.935190, 58.378977],
      country: 'Туркменистан',
    },
    {
      name: 'ОАО «МТЗ»',
      address: 'г. Абуджа',
      status: 3,
      coordinates: [9.067303, 7.509862],
      country: 'Федеративная Республика Нигерия',
    },
    {
      name: 'ОАО «МТЗ»',
      address: 'Боксбург',
      status: 3,
      coordinates: [-26.218844, 28.247084],
      country: 'ЮАР',
    },
    {
      name: 'ОАО «МАЗ»',
      address: 'Обур – Аль-Мардж - Каир',
      status: 3,
      coordinates: [30.050755, 31.246909],
      country: 'Египет',
    },
    {
      name: 'ОАО «МАЗ»',
      address: 'г. Ашгабат',
      status: 3,
      coordinates: [37.920710, 58.396404],
      country: 'Туркменистан',
    },
    {
      name: 'ОАО «МАЗ»',
      address: 'Ha Noi',
      status: 3,
      coordinates: [21.034003, 105.842112],
      country: 'Социалистическая Республика Вьетнам',
    },
    {
      name: 'ОАО «МАЗ»',
      address: 'г. Веньчжоу',
      status: 3,
      coordinates: [27.980929, 120.664700],
      country: 'Китайская Народная Республика',
    },




  ];


